### ISSUE TITLE
CSS 魔法

### ISSUE THREAD

**Issue by liyinkan** [css-conf/1#11]
推荐理由：我至今不知道他的真实名字，但是不妨碍我从他那边偷学很多经验……
话题： 
微博：http://www.weibo.com/cssmagic

**Comment by qushuangru** [comment]
这个魔方也关注着呢。

**Comment by cssmagic** [comment]
很荣幸被圈出来了。
- GitHub： @cssmagic
- 博客： https://github.com/cssmagic/blog/issues

如果近期有研究成果或实践成果，一定和大家分享。

**Comment by dudy5** [comment]
+1
