### ISSUE TITLE
JJ Ying

### ISSUE THREAD

**Issue by liyinkan** [css-conf/1#14]
推荐理由：很强大的设计师
个人主页：http://JJYing.com
微博：http://www.weibo.com/p/1005051645143405

> 因为自己做不好设计，所以从他那里偷学了不少，这事情我不会随便说的……

**Comment by sofish** [comment]
+1 JJ 其实是 Full Stack Designer

**Comment by JJYing** [comment]
受宠若惊呀……我是一只野路子、毫无基本功的业余爱好者……

**Comment by lvwzhen** [comment]
看到 @JJYing 的单页被这么多人抄袭，想着就醉了

**Comment by dudy5** [comment]
希望@JJYing能去
