### ISSUE TITLE
小闷他哥

### ISSUE THREAD

**Issue by yisibl** [css-conf/1#16]
## 推荐理由：
- 小鱼出品，必属精品。无需理由
- 国内著名前端构架，Typo.css作者，github中国区域最活跃coder之一。
- 需要理由吗？需要的话，我也不知道写什么，大家都知道他，人帅，女朋友漂亮，能力又好……
- 好了，想想我就醉了。。。

微博： http://weibo.com/sofish
博客：http://sofi.sh/
Github：https://github.com/sofish

**Comment by linxz** [comment]
又被关了一个，好惨～哈哈哈。

小鱼，你是众望所归啊，不要再关了。
