### ISSUE TITLE
winter程劭非

### ISSUE THREAD

**Issue by Janking** [css-conf/1#17]
推荐理由：基础扎实知识面广泛，在博客中的量少，却质高
github：https://github.com/wintercn
博客：http://winter-cn.cnblogs.com/
微博：http://weibo.com/wintercn

**Comment by wintercn** [comment]
冒个泡，时间合适就去参加

**Comment by yisibl** [comment]
Winter大大的笑容就让我心醉了，一定要去哦。

**Comment by Go7hic** [comment]
我们这些切图的能听到 计子的演讲，想想就醉了

**Comment by smallke** [comment]
支持winter大大....

**Comment by 4tj** [comment]
1024

**Comment by qinmudi** [comment]
+1

**Comment by yisibl** [comment]
Winter(@wintercn) 在我前端之路上给了我很多指引，是良师亦是更好的朋友。其演讲风格幽默风趣，尤其是作为阿里 P8，亦是平易近人，和蔼可亲。非常怀念当初一起在「懒懒交流会」合作系列演讲《贡献标准》 ，平日里也会一起探讨一些很深入的 CSS 细节。我的知乎专栏取名「CSS大草原」也是向 Winter 致敬。

作为一个布道者和演说者，非 Winter 莫属，非常期待！

**Comment by hax** [comment]
附送计子老师最近的噂噂教诲：
http://www.zhihu.com/question/25153900/answer/30223462
http://www.zhihu.com/question/21584213/answer/30689926

**Comment by weiqinan** [comment]
长得帅，听一下可以醉了。

**Comment by zhangmengxue** [comment]
顶~~~

**Comment by makaiqian** [comment]
winter大大....+10086

**Comment by dudy5** [comment]
必须顶啊
