### ISSUE TITLE
赵文博@奇舞团

### ISSUE THREAD

**Issue by jkisjk** [css-conf/1#18]
https://github.com/webzhao
推荐赵文博，奇舞团优质讲师。《HTML5移动网站开发实践.pptx》《探索NodeJS》《闲话网站设计》《Chrome开发工具的秘密》《Css布局。新的可能》，每次分享都是精心准备，让围观的同学受益匪浅。

**Comment by lijinghust** [comment]
听过几次文博的分享，原理理解非常深入，针对问题分析很到位，期待更好更多的分享。

**Comment by ethanzsz** [comment]
文博很赞，推荐~

**Comment by chevion** [comment]
强烈推荐文博，细心、儒雅、文艺派~~

**Comment by melonHuang** [comment]
强烈推荐文博~~~特别好的一个大叔

**Comment by blackMao** [comment]
深入浅出，受益匪浅

**Comment by Elainelele** [comment]
好期待啊！

**Comment by NingningXiao** [comment]
期待ing

**Comment by crossai-2033** [comment]
支持文博

**Comment by liuguanyu** [comment]
支持文博

**Comment by fefit** [comment]
文博涉猎广泛，讲解透彻，支持+期待！

**Comment by dudy5** [comment]
期待ing
