### ISSUE TITLE
林小志

### ISSUE THREAD

**Issue by sofish** [css-conf/1#2]
**推荐理由**：最早接触，至今仍没有放下代码
- 中国最早接触 CSS 的一批人，《CSS 那些事》作者
- 携程网 CSS 专家
- Blueidea（还有人知道吗？）Web 开发版主

**微博**：http://weibo.com/linxz428

![](http://tp1.sinaimg.cn/1422502380/180/5606790361/1)

**Comment by jornakbobo** [comment]
css权威代表

**Comment by showzyl** [comment]
小志给力。

**Comment by Hsinglin** [comment]
顶小志。

**Comment by jianjiade** [comment]
css那些事儿 的作者 赞一个

**Comment by linxz** [comment]
呃……这个我可以说我什么都不知道么。@sofish，你应该找一下彪叔、pufen、tommy、艾文、神飞、大猫等等人啊，然后还有在上海的大漠、文彬，杭州那边的一丝等人嘛～～我这个还是退下来吧～

**Comment by sofish** [comment]
@linxz 你要做模板

**Comment by f2er** [comment]
前辈～～前端指路灯

**Comment by linxz** [comment]
呃……模版～～～好吧，那我就放心了～～我只是一个模板而已！@sofish，我想来想去，觉得模板应该是你自己～～～

**Comment by sofish** [comment]
@linxz 我错了。你是模范

**Comment by Go7hic** [comment]
醉了。。前端指明灯

**Comment by elrrrrrrr** [comment]
小志＋1

**Comment by hoosin** [comment]
顶小志。

**Comment by huang-snail** [comment]
顶小志

**Comment by lenage** [comment]
blueidea 蓝色理想，

**Comment by lyushine** [comment]
小志＋1

**Comment by ghost** [comment]
小志＋1

**Comment by airen** [comment]
必须顶起导师级人物，林小志

**Comment by ccirene** [comment]
小志+1 不上对不起民众，雄起吧

**Comment by FEsy** [comment]
顶小志

**Comment by aliang007** [comment]
看小志的css长大的

**Comment by vingojw** [comment]
看小志的css长大的

**Comment by 06wj** [comment]
看小志的css长大的

**Comment by lwbjing** [comment]
看小志的css长大的

**Comment by mypianpian** [comment]
哇~ 小志GG好厉害！

**Comment by willyang** [comment]
linxz就是我前端路上的指路明灯啊

**Comment by crazybull** [comment]
linxz就是我前端路上的指路明灯啊

**Comment by thomasyus** [comment]
小志GG就是我前端路上的指路明灯啊，看小志GG的书长大的~小志GG长得帅，技术牛逼人人爱~

**Comment by prgg** [comment]
前来膜拜！

**Comment by sgpyvip** [comment]
支持小志GG！

**Comment by cailei876** [comment]
小志GG就是我前端路上的指路明灯啊！必须上啊！

**Comment by txji** [comment]
小志 +1

**Comment by smallke** [comment]
支持小志叔+10086

**Comment by Keystion** [comment]
支持志哥

**Comment by catsjungle** [comment]
支持+1

**Comment by liyinkan** [comment]
当我看到

> sofish added `不参与` and removed `推荐讲师` labels 2 hours ago

的时候我只想说：我也是看小志的书长大的。

**Comment by stuxt** [comment]
顶+1，CSS大佬~

**Comment by Mingdy** [comment]
支持俺的偶像，小志哥哥 +1 ~

**Comment by jruif** [comment]
学css大多都是看的他博客开始的

**Comment by ideazhao** [comment]
顶志哥，顶志哥，原因不用说~

**Comment by bailnl** [comment]
志爷，bailnl来顶你了

**Comment by f2ebill** [comment]
顶起，不过很希望在上海附近举办啊，志哥去了我肯定去捧场啊。北京好远的
