### ISSUE TITLE
点头猪

### ISSUE THREAD

**Issue by jianjiade** [css-conf/1#20]
推荐理由：点头猪，必须推荐。

个人简介：一个靠脸和CSS吃饭的妹子，在功未成名未就的时候转去做交互了，力争做个技术圈里最懂设计的，设计圈里最懂技术的~

个人微博：<a href='http://weibo.com/lilyxue' target='_blank'>点头猪</a>

<img src='http://ww2.sinaimg.cn/mw690/6204189fjw8ecjwlpwneqj20hs0hsq3z.jpg' width=200  alt='点头猪'/>

**Comment by ghost** [comment]
羡慕靠脸吃饭的！+1

**Comment by liuyanghejerry** [comment]
+999

**Comment by Janking** [comment]
+1024

**Comment by yisibl** [comment]
羡慕靠脸吃饭的！+1

**Comment by joden2014** [comment]
+10086

**Comment by ghost** [comment]
羡慕靠脸吃饭的！+1

**Comment by amio** [comment]
顶薛导！

**Comment by stuxt** [comment]
+233333

**Comment by SunLn** [comment]
羡慕靠脸吃饭 ++1

**Comment by qinmudi** [comment]
同羡慕靠脸吃饭 +1

**Comment by dudy5** [comment]
+1

**Comment by annilq** [comment]
这个大会是在哪里呀...

**Comment by dudy5** [comment]
北京航空航天大学

发自我的 iPhone

**Comment by markyun** [comment]
羡慕靠脸吃饭的！+1

**Comment by Niefee** [comment]
路过
