### ISSUE TITLE
田乐（diamondtintin）

### ISSUE THREAD

**Issue by hoosin** [css-conf/1#21]
![diamondtin](http://tp2.sinaimg.cn/1640031857/180/5599823608/1)

推荐理由：理想主义者，完美主义者，走出中国的WEB前后端程序员，Beijing Open Party组织者，目前定居在美国旧金山。
微博：http://weibo.com/u/1640031857
instagram：diamondtin

他在国内社交网络比较低调，很多朋友可能不知道他，曾经看过他回答的一个css问题，看醉了。[在 CSS 中，用 float 和 position 的区别是什么？](http://www.zhihu.com/question/19588854/answer/12310963)

**Comment by wileam** [comment]
顶机器猫tin老师~but感觉他不一定能回来呢

**Comment by hoosin** [comment]
@wileam 我已经在联系他了

**Comment by itchina110** [comment]
@hoosin 联系的结果是？

**Comment by dudy5** [comment]
+1
