### ISSUE TITLE
寸志

### ISSUE THREAD

**Issue by hoosin** [css-conf/1#22]
![cunzi](http://hiphotos.baidu.com/baidu/pic/item/f31fbe096b63f6240a7ae88c8544ebf81a4ca31e.jpg)

推荐理由：文艺前端程序员，目前就职Teambition，[CoffeeScript小书](http://yuedu.baidu.com/ebook/2000ed892cc58bd63186bdb3)作者，《深入浅出CoffeeScript》译者，《Node.js实战》作者之一。

微博：http://weibo.com/chromeappsstore

**Comment by island205** [comment]
没好好写过 css，不来丢人了，先报名参会吧！

**Comment by elrrrrrrr** [comment]
寸老师 +1 !

**Comment by shuding** [comment]
寸老师 +1！

**Comment by SuneBear** [comment]
寸老师 +1！

**Comment by beforeload** [comment]
寸老师+1!

**Comment by dudy5** [comment]
+1
