### ISSUE TITLE
情封

### ISSUE THREAD

**Issue by jianjiade** [css-conf/1#23]
推荐理由：福建前端联盟 联合创始人之一，4399前端负责人，前端de早读课站长，致力于推进前端的发展

微博：<a href="http://weibo.com/206234546" target="_blank">情封</a>

<img src="http://ww4.sinaimg.cn/mw690/685046e3gw1ehsemlm70bj20c80lqwgf.jpg" width=200 alt="情封" />

**Comment by hoosin** [comment]
顶封儿

**Comment by jamiesoung** [comment]
为什么情封大大上班的时候会有游泳眼镜....

**Comment by stuxt** [comment]
顶情疯大神

**Comment by Go7hic** [comment]
情封这眼睛也是醉了

**Comment by smallke** [comment]
顶封儿,顺便求情大大眼睛同款

**Comment by dudy5** [comment]
+1
