### ISSUE TITLE
给力 @hoosin

### ISSUE THREAD

**Issue by justJavaScript** [css-conf/1#24]
![hoosin](http://tp2.sinaimg.cn/2080465705/180/5700808450/1)

推荐理由：一个乐于分享，GEEK精神十足的程序员，最早写C++转型前端代码的程序员，热衷前端圈的发展，致力于推进前端的发展，目前坐标在广州。

微博：http://weibo.com/273500363

**Comment by Go7hic** [comment]
+1
总奸带我装逼带我飞
