### ISSUE TITLE
董福興

### ISSUE THREAD

**Issue by hax** [css-conf/1#26]
推荐讲师：董福興（http://www.zhihu.com/people/BobbyTung/about）

**Comment by hax** [comment]
建议topic：css中文排版相关标准的未来

**Comment by bobbytung** [comment]
不敢當，我也是開始學EPUB 3後才接觸CSS。但一下子栽得深點，馬上就到W3C去處理中文排版的事情。我唯一的優點就是會說中文吧。
另外也推薦村上真雄，他早先在Antenna House做工具，幫O'reilly實踐了HTMLBook出印刷用PDF的工作流程。而Bert Bos與Håkon Wium Lai一直以來都是CSS排版的教祖。

**Comment by yisibl** [comment]
@bobbytung 你要入职 W3C 啦？

**Comment by bobbytung** [comment]
@yisibl 沒啦，還是在EPUB上撐著。

**Comment by yisibl** [comment]
@bobbytung 期待来给我们分享啊！

**Comment by dudy5** [comment]
+1

**Comment by hax** [comment]
@bobbytung 第二届（8月8日）有空来分享么？讲讲 clreq？

**Comment by bobbytung** [comment]
@hax 剛才看到。剛好卡在兩次演講間，下一週在台灣有個Coscup，應該無法參加。

**Comment by hax** [comment]
@bobbytung 呃，遗憾。
