### ISSUE TITLE
林克寰

### ISSUE THREAD

**Issue by hax** [css-conf/1#27]
Web无障碍专家，《[网页亲和力](http://book.douban.com/subject/6808975/)》作者，《[Transcending CSS](http://book.douban.com/subject/1927733/)》[繁体中文版](http://book.douban.com/subject/2125561/)译者。

**Comment by itchina110** [comment]
jedi呀？

**Comment by hax** [comment]
嗯，多找台湾人，做有利于两岸交流的事，呵呵呵呵。

**Comment by itchina110** [comment]
jedi 也没有时间过来，医学方面的会特别多，没时间过来

**Comment by dudy5** [comment]
+
