### ISSUE TITLE
贺师俊

### ISSUE THREAD

**Issue by Justineo** [css-conf/1#28]
Hax，目前就职于百姓网（不知是否有变化，求证）。
知乎：http://www.zhihu.com/people/he-shi-jun
博客：http://hax.iteye.com/blog/

每次不管是看贺老的博客、知乎回答还是他在 W3C 一堆邮件组的回复，都有新的收获。

**Comment by wintercn** [comment]
顶贺老

**Comment by Go7hic** [comment]
这 Web 开发大师级别的人物啊。。膜拜+推荐

**Comment by doyoe** [comment]
贺老，推荐

**Comment by lilyxue** [comment]
大神级的，+1

**Comment by itchina110** [comment]
+1

**Comment by cssmagic** [comment]
+1

微博： http://weibo.com/haxy
GitHub： @hax

贺老在百姓网，是我的导师。我在百姓网的很多实践都是在贺老的启发和指导下完成的。

**Comment by hax** [comment]
@cssmagic 不要说得好像我比你还老似的…… `@_@`

**Comment by sofish** [comment]
@hax @cssmagic 哈哈哈哈哈哈哈哈，我要笑屎了

**Comment by lost-an** [comment]
顶贺老！

**Comment by liyinkan** [comment]
为什么不是老贺而是贺老……

**Comment by itchina110** [comment]
贺老 表示他是权威。
老贺 是指他年龄比较大了。
嘿嘿

**Comment by yisibl** [comment]
国内最具批判精神的工程师（Fuck OOCSS, BEM），每次与之交谈都获益良多，是我成长路上的良师益友。CSS 方面，从鲜有问津的排版到最新的Grid布局都有极其深入的研究，再到「margin/padding垂直方向百分比为何按照父元素宽度计算」深入本质的思考，都深深令人折服。在CSS还原设计，CSS工程化方面的思维观点领先国内前端工程师至少三年。

我最期待的 CSS 讲师之一。

以上。

**Comment by Rayi** [comment]
贺老是一个幽默风趣的已婚男人啊，其批判性的讲话内容会让分享显的充满活力。墙裂顶贺老~~~

**Comment by dudy5** [comment]
久闻贺老大名，作为前辈，非常期待贺老的出席

**Comment by maicss** [comment]
已婚了啊。感觉很神奇，我第一次知道他是他在知乎“工作”，后来怎么去了百姓？感觉是一个刚毕业的大学生....
