### ISSUE TITLE
fantasai

### ISSUE THREAD

**Issue by tommyjtl** [css-conf/1#29]
- Mozilla 1999 –
- www-style 2000 –
- CSSWG spec-writer 2004 –
- @fantasai
- [Mailing List](http://markmail.org/search/?q=fantasai%40escape.com)

**Comment by bobbytung** [comment]
Fantasai是主要負責CSS Text、CSS Writing-mode幾個與CJK語文相關Module的Editor。也因為這樣，長跑日本台灣與中國，而日本跑得最多。推薦靠這機會籠絡一下。

**Comment by yisibl** [comment]
上次W3C年会上，与 Fantasai 简单了聊了一下 Flex 规范现有的问题，非常可惜只有短短的十分钟时间，期待有更多的机会。

Fantasai 本人还会说一点中文，据上次的不完全统计，除了 Tab，她是编写最多CSS规范的编辑。

**Comment by Janking** [comment]
高大上…草根F2E何时才能拉近与大神的距离啊……

**Comment by ourai** [comment]
@Janking 少说废话都做实事就能。

**Comment by kennyluck** [comment]
fantasai++ 她去我就去，她不去我就不去。

**Comment by dudy5** [comment]
+1

**Comment by itchina110** [comment]
我们请她了，不过请得太晚了，她没办法来，可惜！

**Comment by bobbytung** [comment]
推薦另外一位講者Lea Verou，她也是前W3C Stuff
http://lea.verou.me
最近完成一本新書"CSS Secrets"
http://shop.oreilly.com/product/0636920031123.do
這本書他用CSS排版做成，也是一直以來關注CSS排版的技術人員。

**Comment by airen** [comment]
最近正在读这本书，的确很有意思
