### ISSUE TITLE
推荐你最想听的讲师和话题

### ISSUE THREAD

**Issue by sofish** [css-conf/1#3]
开一个 issue。写上你的推荐理由（自荐就更好了），然后，分享出去吧。
- 推荐理由
- 话题（你想听什么）
- GitHub / 博客 / 微博 等地址（让大家更了解 TA）

可以参照 #2

**Comment by yisibl** [comment]
必须上 Github 啊。。。

**Comment by sofish** [comment]
@yisibl 已加

**Comment by dorisgirl** [comment]
张克军~~~

**Comment by Janking** [comment]
张鑫旭！

**Comment by sofish** [comment]
@dorisgirl 开 issue 啊！
@Janking 已经有人开了 #12

**Comment by zengjialuo** [comment]
@Justineo
百度ECOM视觉方向负责人
https://github.com/ecomfe/est
http://www.zhihu.com/people/justineo

**Comment by sofish** [comment]
@zengjialuo 新开个 issue 吧=
