### ISSUE TITLE
CSS联合发明人：Bert Bos

### ISSUE THREAD

**Issue by itchina110** [css-conf/1#30]
CSS共同发明人。

目前还在W3C

http://www.w3.org/People/Bos/

Bert Bos completed his Ph.D. in Groningen, The Netherlands, on a prototyping language for graphical user interfaces. He then went on to develop a browser targeted at humanities scholars, before joining the W3C at INRIA/Sophia-Antipolis in October 1995. He is co-inventor of CSS and created & led W3C's Internationalization activity. After working on HTML and XML, he is now leading the CSS and Mathematics activities.

**Comment by bobbytung** [comment]
既然提了Bert Bos，不妨找Opera贊助，順便把Håkon Wium Lai也找來？

**Comment by tommyjtl** [comment]
@bobbytung +1

**Comment by hax** [comment]
我其实特别想听听 Håkon Wium Lai 谈谈他对 CSS regions 的意见。

**Comment by itchina110** [comment]
Håkon Wium 已经邀请了，没时间来

**Comment by itchina110** [comment]
正在和Bert Bos 确认时间。

**Comment by hax** [comment]
好吧，我想听 Bert Bos 谈预处理器特性引入 CSS 的利弊，呵呵。

**Comment by itchina110** [comment]
已经和 Bert Bos确认了，他时间没有问题。现在需要找到1W元赞助，为他提供差旅费用。

**Comment by kennyluck** [comment]
把钱浪费在 Bert Bost 上还不如找 fantasai。

**Comment by itchina110** [comment]
我们同时也想请fantasai，不过好像fantasai不愿意或者没时间出席。

**Comment by hax** [comment]
@kennyluck 不要这么吐槽 Bert 老大爷呀。

**Comment by dudy5** [comment]
Bert Bos都要过来了，怎么能不顶一下呢，顶起
