### ISSUE TITLE
薛良斌

### ISSUE THREAD

**Issue by bobbytung** [css-conf/1#31]
[個人簡介](http://iamhlb.com/about)

台灣和多（Handlino）的創辦人與UI設計師，被KKBOX併購後進去工作。

不過這都不重要，[Fire.app](http://fireapp.kkbox.com)這個設計工具在台灣蠻火紅的。

作為參考。

**Comment by itchina110** [comment]
赞hlb，2011年在上海的拥抱HTML5，有出席。

演讲的内容非常的赞，非常的幽默。

**Comment by hlb** [comment]
感謝推薦，不過最近的技能只剩下用嘴巴寫程式，以及按 GitHub 的綠色 merge pr 按鈕而已 ^_^;

**Comment by dudy5** [comment]
+1
