### ISSUE TITLE
Ghost Zhang

### ISSUE THREAD

**Issue by sofish** [css-conf/1#33]
很早期当大家都不在谈兼容技巧的时候，他已经在开始淡如果去做模块化。似乎是从大四开始，从他的博客得到很多启发。

博客：http://blog.cssforest.org/

**Comment by itchina110** [comment]
鬼哥不错

**Comment by ideazhao** [comment]
鬼哥肯定要顶啊，专注重构这么多年！~

**Comment by dudy5** [comment]
+1
