### ISSUE TITLE
勾三股四

### ISSUE THREAD

**Issue by liyinkan** [css-conf/1#34]
Sass and Compass in Action 译者
微博：http://weibo.com/mx006

> 样式表是前端工程师几乎每天上班都会碰面打招呼的挚友。而在我看来，它同时也是一项被同行们严重低估的技术。很多人觉得样式表就是CSS，写起来繁琐、枯燥又没有技术含量。但很少有人为此而思考：这是命中注定的吗？撰写样式表就应该是现在这个方式，还仅仅是因为我们习惯了撰写CSS？也许我们的工作可以更简单、更顺畅、效果更好？—— Sass and Compass in Action 译者序

**Comment by hoosin** [comment]
推荐讲师

**Comment by sofish** [comment]
+1

**Comment by wileam** [comment]
+1

**Comment by dudy5** [comment]
+1
