### ISSUE TITLE
拴萝卜的棍子（毛竹自荐）

### ISSUE THREAD

**Issue by leeluolee** [css-conf/1#35]
**毫无节操廉耻的毛遂自荐**，惯例基本信息：
- Github: [@leeluolee](https://github.com/leeluolee)
- 微博: [@拴萝卜的棍子](http://weibo.com/luobolee/)
- 就职于网易杭州的仍需靠加班维持生计的基层码农

无名小卒一名，但是如果有人对于**css预处理器这个方向有兴趣**，相信你会对我的分享感兴趣。

如果你希望听到：
1. 为什么会有css预处理器，以及css预处理器的历史，它解决了css什么问题
2. 如何从原始css代码去逐步抽象化你的css模块
3. 大型项目中(~10人前端)，我们如何组织和管理css预处理模块？如何保持通用性
4. mixin和extend分别可能带来的问题，less、sass以及mcss的这两个常规特性的微妙区别.
5. css预处理器的坑、性能问题，未来还需不需要预处理器
6. 等等等...

**深度和广度**是可以保证的  

在此领域作的品
1. [mcss](https://github.com/leeluolee/mcss)。一言介绍：**函数为first-class** 的css预处理器，这是语言级的可能性问题，所以我只提了这点，当然mcss在设计上也思考了stylus存在的问题
2. [mass](https://github.com/leeluolee/mass)。基于ls的函数库，看下css3的源码以及effect的api，然后思考用其它预处理器可以实现么？

事实上这个预处理器接近1年没有进行继续进展，其中的缘由和sass和less的火爆完全没有关系，而是由于作者看好[rework](https://github.com/reworkcss/rework)的出现。但是近段时间看来，rework的极致的模块细分带来的低耦合性也带来了高的安装配置成本，似乎推广也不是好。我已经怀疑我的原先看法了，嗯...

**Comment by Janking** [comment]
marrk！

**Comment by hax** [comment]
看上去很不错啊！对了，mcss/mass的链接修一下呗！

**Comment by lzf0402** [comment]
up！

**Comment by zjuwwq** [comment]
abstract，函数作为first-class都是很有想法的设计

**Comment by Tankpt** [comment]
支持大大

**Comment by leeluolee** [comment]
@ljgeneral 要不要这么浮夸。。。

**Comment by moretwo** [comment]
一直在关注学习mcss；看作者的拴屎棍的萝卜，好想认识并深入了解作者@leeluolee，从作者身上学到了不少东西，支持作者

**Comment by lwbjing** [comment]
支持自荐~~

**Comment by unbug** [comment]
推荐啊，拴萝卜的棍子的思路总是比较清晰而且深入的
