### ISSUE TITLE
尤小右（自荐啦）

### ISSUE THREAD

**Issue by yyx990803** [css-conf/1#36]
微博：[@尤小右](http://www.weibo.com/1761511274/profile)

正好 1 月份会在国内。过去两年在 Google Creative Lab 期间做了大量的基于 CSS transition/transform 的动态界面，所以希望可以从这个角度做一些分享：
- CSS 到底能让我们在移动端做到什么程度？媲美原生的体验到底是否可能？
- Vue.js 以及其他主流框架的动画系统实现
- 原生级界面动效的可能方案

**Comment by hkz404** [comment]
虽然不能去现场，不过相当支持，平时工作的内容需要用到大量的 CSS 动画，对你的分享很感兴趣。

**Comment by stuxt** [comment]
这个逼格绝对够了~
支持

**Comment by hirokith** [comment]
顶，期待！
