### ISSUE TITLE
周文彬

### ISSUE THREAD

**Issue by showzyl** [css-conf/1#4]
推荐理由：文彬对于css3动画领域研究比较深刻，希望听到他的分享。

微博：http://weibo.com/wenbin1986
个人博客：http://www.zhouwenbin.com/

@sofish

**Comment by sofish** [comment]
我也很喜欢文彬写的动画

**Comment by FEsy** [comment]
周哥，动画真心挺赞，顶

**Comment by dudy5** [comment]
研究过图形与动画的应该都知道的，顶起

**Comment by liuyanghejerry** [comment]
+1
