### ISSUE TITLE
廖伟华（大漠w3cplus）

### ISSUE THREAD

**Issue by linxz** [css-conf/1#5]
推荐理由：大漠一直致力于CSS3、SASS等方面的研究，并且还是《图解CSS3》的作者，相信在国内也是有一定的影响力的……

微博：[http://weibo.com/311290005](http://weibo.com/311290005)
博客：[http://w3cplus.com](http://www.w3cplus.com)

![大漠](http://www.w3cplus.com/sites/default/files/header.jpg)

**Comment by jianjiade** [comment]
w3cplus 是我前端路上的指明灯~

赞一个

**Comment by sofish** [comment]
大漠最近在搞的 Sass 项目很不错啊

**Comment by vingojw** [comment]
顶起

**Comment by airen** [comment]
我就一打酱油和切图的，上不了台面。强力推荐@sofish、@一丝姐姐、@林小志、＠点头猪等等，这些大牛都杠杠的

**Comment by yisibl** [comment]
+1

**Comment by NingningXiao** [comment]
很喜欢w3cplus呀

**Comment by smallke** [comment]
前排顶群主+1

**Comment by ideazhao** [comment]
大漠哥要去的，这个必须要得，听其一席话胜读n年书的境界

**Comment by simaQ** [comment]
+1

**Comment by ghost** [comment]
顶一个顶一个

**Comment by baixiaosh** [comment]
顶一个顶一个

**Comment by dudy5** [comment]
大漠哥的CSS实力先就不说了，那是杠杠的，没得话说的，就说大漠哥在学习前端技术方面的学习态度、学习能力之类的，也足以为我辈的楷模了

**Comment by wkylin** [comment]
一直在紧随，从未接近，努力中......

**Comment by kai517** [comment]
顶一个
