### ISSUE TITLE
瑶姐（doyoe）

### ISSUE THREAD

**Issue by sunorry** [css-conf/1#8]
**推荐理由**： 顶级的 CSS 专家，看他的 `margin` 系列让我醉生梦死
**Blog**： http://www.doyoe.com/  (里面有手册，实验室与博客)
**微博**：http://weibo.com/doyoe

**Comment by jianjiade** [comment]
看瑶姐的margin系列文章，回想一下，都醉了

**Comment by Janking** [comment]
瑶姐的margin系列文章确实赞！！

**Comment by yisibl** [comment]
+1

**Comment by doyoe** [comment]
呃

**Comment by angrytoro** [comment]
顶妩媚的瑶姐~~

**Comment by ideazhao** [comment]
瑶姐的手册做的相当好，要不瑶姐就去把手册从头到尾讲一遍吧，呵呵，顶瑶姐

**Comment by liaobin312716** [comment]
期待中...

**Comment by dudy5** [comment]
期待中....

**Comment by dudy5** [comment]
家中常备瑶姐的手册
